### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read'

### ISSUE THREAD

**Issue by Abuelodelanada** [PietroPasotti/ops-scenario#3]
Runing the following test:

```python
@patch("charm.KubernetesServicePatch")
@patch("lightkube.core.client.GenericSyncClient")
@patch("charm.TraefikIngressCharm.external_host", PropertyMock(return_value="foo.bar"))
def test_start(*_):
    charm_spec = CharmSpec.from_charm(TraefikIngressCharm)
    # equivalent to:
    # META = yaml.safe_load((Path(__file__).parent.parent.parent / "metadata.yaml").read_text())
    # ACTIONS = yaml.safe_load((Path(__file__).parent.parent.parent / "actions.yaml").read_text())
    # CONFIG = yaml.safe_load((Path(__file__).parent.parent.parent / "config.yaml").read_text())
    # charm_spec = CharmSpec(TraefikIngressCharm, meta=META, config=CONFIG, actions=ACTIONS))

    scenario = Scenario(charm_spec=charm_spec)
    scenario.play(Scene(
        state=State(
            # ATM scenario can't use the defaults specified in config.yaml, so we need to provide ourselves the values
            # of each config option
            config={"routing_mode": "path"},
            # you need to specify which containers are present, otherwise the charm will raise exceptions when
            # assuming that there is a "traefik" container.
            containers=[
                ContainerSpec(name="traefik",
                              # we need to set can_connect=False for now because I didn't write yet the mocking code for
                              # the other pebble interactions yet. So if the charm tries to get_services, get_plan,
                              # push, pull etc, there will be errors.
                              # Can implement this tomorrow so you can proceed.
                              can_connect=False)
            ]),
        event=event("start")))

```

I get:

```sh
Traceback (most recent call last):
  File "/home/jose/trabajos/canonical/repos/traefik-k8s-operator/tests/scenario/test_setup.py", line 26, in test_start
    charm_spec = CharmSpec.from_charm(TraefikIngressCharm)
  File "/home/jose/.local/lib/python3.10/site-packages/scenario/structs.py", line 244, in from_charm
    meta = yaml.safe_load(charm_root / 'metadata.yaml')
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/jose/.local/lib/python3.10/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'PosixPath' object has no attribute 'read'
```

As far as I understand the issue is in `CharmSpec.from_charm` method... we are trying to `yaml.safe_load` a path rather than string that contains the yaml.

This may fix the issue:

```python
    @staticmethod
    def from_charm(charm_type: Type["CharmType"]):
        charm_source_path = Path(inspect.getfile(charm_type))
        charm_root = charm_source_path.parent.parent

        meta = yaml.safe_load(Path(charm_root, 'metadata.yaml').read_text())
        actions = config = None

        config_path = charm_root / 'config.yaml'
        if config_path.exists():
            config = yaml.safe_load(config_path.read_text())

        actions_path = charm_root / 'actions.yaml'
        if actions_path.exists():
            actions = yaml.safe_load(actions_path.read_text())

        return CharmSpec(
            charm_type=charm_type,
            meta=meta,
            actions=actions,
            config=config
        )
```

**Comment by PietroPasotti** [comment]
ah yeah, I fixed that already but didn't push. Thanks!
